version: '3.7'

services:
  daily-diet-postgres:
    image: bitnami/postgresql:latest
    container_name: daily-diet-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=dailydiet